version: '3.8' # Hoặc "3"

services:
  app:
    build: .
    ports:
      - '5000:5000'
    env_file:
      - .env
    command: /usr/local/bin/wait-for-it.sh db:3306 -- npm start
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
